<#
.SYNOPSIS
  Normalize multi-platform chapter markdown files to align with platform_validate gates (WITHOUT auto-padding).

.DESCRIPTION
  - Reads the same config JSON used by scripts/platform_validate.ps1.
  - Ensures the afterword marker exists.
  - Optionally removes legacy PAD_TO_GATE/UID-like padding paragraphs (RefreshPadding).
  - For English afterword max-words gates: trims afterword to max words (best-effort).

  NOTE
    This script intentionally DOES NOT auto-generate/pad synthetic filler to meet min gates.
    If an output does not meet minCJK/minLen/minAfterword thresholds, fix the content by rewriting.

  IMPORTANT: This script does NOT print chapter正文; it only prints numeric metrics.

.USAGE
  ./scripts/pad_to_gate.ps1 -ConfigPath "SOP执行日志/平台校验_1.1.7_2026-02-11.config.json"

#>

[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [string]$ConfigPath,

  [Parameter()]
  [switch]$WhatIf,

  # When set, remove previously auto-padded paragraphs (generated by this script)
  # and regenerate padding even if gates are already satisfied.
  [Parameter()]
  [switch]$RefreshPadding
)

Set-StrictMode -Version Latest

$CjkRe = [regex]'[\u4e00-\u9fff]'
$WordRe = [regex]"[A-Za-z]+(?:'[A-Za-z]+)?|\d+"

function Read-TextBestEffort {
  param([Parameter(Mandatory=$true)][string]$Path)

  try {
    return Get-Content -LiteralPath $Path -Raw -Encoding UTF8 -ErrorAction Stop
  } catch {
    try {
      return Get-Content -LiteralPath $Path -Raw -Encoding Default -ErrorAction Stop
    } catch {
      try {
        $gb18030 = [System.Text.Encoding]::GetEncoding(54936)
        return [System.IO.File]::ReadAllText((Resolve-Path -LiteralPath $Path).Path, $gb18030)
      } catch {
        return ""
      }
    }
  }
}

function Get-Marker {
  # Build "## 作者有话说" from code points for Windows PowerShell 5.1 stability.
  return '## ' + ([char]0x4F5C) + ([char]0x8005) + ([char]0x6709) + ([char]0x8BDD) + ([char]0x8BF4)
}

function Split-BodyAfterword {
  param(
    [Parameter(Mandatory=$true)][string]$Text,
    [Parameter(Mandatory=$true)][string]$Marker
  )

  $idx = $Text.IndexOf($Marker, [System.StringComparison]::Ordinal)
  if ($idx -ge 0) {
    $body = $Text.Substring(0, $idx)
    $after = $Text.Substring($idx + $Marker.Length)
    $after = ($after -replace '^[ \t\r\n]+', '')
    return ,@($body, $after, $true)
  }

  return ,@($Text, "", $false)
}

function Get-JsonProp {
  param(
    [Parameter(Mandatory = $true)]$Obj,
    [Parameter(Mandatory = $true)][string]$Name,
    [Parameter(Mandatory = $true)]$Default
  )

  if ($null -eq $Obj) { return $Default }
  $p = $Obj.PSObject.Properties[$Name]
  if ($null -eq $p) { return $Default }
  $v = $p.Value
  if ($null -eq $v) { return $Default }
  return $v
}

function ConvertTo-NormalizedText {
  param(
    [Parameter(Mandatory=$true)]
    [AllowEmptyString()]
    [string]$Text
  )

  # Normalize newlines, trim trailing spaces, ensure final newline.
  $t = $Text -replace "`r`n", "`n"
  $lines = $t -split "`n", -1
  for ($i = 0; $i -lt $lines.Count; $i++) {
    $lines[$i] = $lines[$i].TrimEnd()
  }
  $t2 = ($lines -join "`n")
  if (-not $t2.EndsWith("`n")) { $t2 += "`n" }
  return $t2
}

function Remove-PadToGateParagraphs {
  param(
    [Parameter(Mandatory=$true)][string]$Text
  )

  # Old versions appended paragraphs containing UIDs like: <platform>-<10hex>-<3digits>
  # New versions will include explicit PAD_TO_GATE markers.
  $uidRe = [regex]'\-[0-9a-f]{10}\-\d{3}'
  $markerRe = [regex]'PAD_TO_GATE'

  $t = $Text -replace "`r`n", "`n"
  $paras = $t -split "\n\s*\n", -1
  $kept = New-Object System.Collections.Generic.List[string]
  foreach ($p in $paras) {
    if ([string]::IsNullOrWhiteSpace($p)) { continue }
    if ($uidRe.IsMatch($p) -or $markerRe.IsMatch($p)) {
      continue
    }
    $kept.Add($p.TrimEnd())
  }
  if ($kept.Count -eq 0) { return "" }
  return ($kept -join "`n`n") + "`n"
}

# Load config
if (-not (Test-Path -LiteralPath $ConfigPath)) {
  throw "Config file not found: $ConfigPath"
}

$cfgText = Read-TextBestEffort -Path $ConfigPath
$cfg = $cfgText | ConvertFrom-Json
$items = @($cfg.files)
$defaultMarker = Get-Marker
$zhMarker = $defaultMarker
$zhTitle = '' + ([char]0x4F5C) + ([char]0x8005) + ([char]0x6709) + ([char]0x8BDD) + ([char]0x8BF4)
$zhMarkerLooseRe = [regex]('##\s*' + [regex]::Escape($zhTitle))

$results = @()

foreach ($item in $items) {
  $platform = [string]$item.platform
  $path = [string]$item.path

  $minCJK = [int](Get-JsonProp -Obj $item -Name 'minCJK' -Default 0)
  $maxCJK = [int](Get-JsonProp -Obj $item -Name 'maxCJK' -Default 0)
  $requireAfterword = [bool](Get-JsonProp -Obj $item -Name 'requireAfterword' -Default $false)
  $minAfterwordCJK = [int](Get-JsonProp -Obj $item -Name 'minAfterwordCJK' -Default 0)
  $maxAfterwordCJK = [int](Get-JsonProp -Obj $item -Name 'maxAfterwordCJK' -Default 0)
  $minAfterwordWords = [int](Get-JsonProp -Obj $item -Name 'minAfterwordWords' -Default 0)
  $maxAfterwordWords = [int](Get-JsonProp -Obj $item -Name 'maxAfterwordWords' -Default 0)

  $minLen = [int](Get-JsonProp -Obj $item -Name 'minLen' -Default 0)
  $maxTotalCJKProp = $item.PSObject.Properties['maxTotalCJK']
  $maxTotalCJK = $(if ($null -ne $maxTotalCJKProp -and $null -ne $maxTotalCJKProp.Value) { [int]$maxTotalCJKProp.Value } else { $null })
  $requireNoCJK = ($null -ne $maxTotalCJK -and $maxTotalCJK -eq 0)

  $marker = [string](Get-JsonProp -Obj $item -Name 'afterwordMarker' -Default $defaultMarker)

  if (-not (Test-Path -LiteralPath $path)) {
    $results += [pscustomobject]@{ platform=$platform; path=$path; action='missing'; changed=$false }
    continue
  }

  $text = Read-TextBestEffort -Path $path
  if ([string]::IsNullOrWhiteSpace($text)) {
    $results += [pscustomobject]@{ platform=$platform; path=$path; action='empty'; changed=$false }
    continue
  }

  # If this is an English/no-CJK gate, remove any stray Chinese marker section appended by mistake.
  if ($requireNoCJK -and ($marker -ne $zhMarker)) {
    # Accept loose whitespace between '##' and the Chinese title.
    $mZh = $zhMarkerLooseRe.Match($text)
    if ($mZh.Success) {
      $text = ($text.Substring(0, $mZh.Index)).TrimEnd() + "`n"
    }
  }

  # If the file is required to have 0 CJK, refuse to proceed if CJK is already present (after cleanup).
  if ($requireNoCJK -and ($CjkRe.Matches($text).Count -gt 0)) {
    $results += [pscustomobject]@{ platform=$platform; path=$path; action='blocked_cjk'; changed=$false }
    continue
  }

  $changed = $false

  if ($text.IndexOf($marker, [System.StringComparison]::Ordinal) -lt 0) {
    # Add marker if missing
    $text = ConvertTo-NormalizedText -Text $text
    $text = $text.TrimEnd() + "`n`n$marker`n"
    $changed = $true
  }

  $parts = Split-BodyAfterword -Text $text -Marker $marker
  $body = [string]$parts[0]
  $after = [string]$parts[1]

  if ($RefreshPadding) {
    # Remove old PAD_TO_GATE/UID-like padding paragraphs.
    $body2 = Remove-PadToGateParagraphs -Text $body
    $after2 = Remove-PadToGateParagraphs -Text $after
    if ($body2 -ne $body -or $after2 -ne $after) {
      $changed = $true
      $body = $body2
      $after = $after2
    }
  }

  $bodyCjk = $CjkRe.Matches($body).Count
  $afterCjk = $CjkRe.Matches($after).Count
  $afterWords = $WordRe.Matches($after).Count

  # IMPORTANT: Auto-padding/padding-to-min-gates has been removed on purpose.
  # This script will NOT attempt to reach minCJK/minLen/minAfterword thresholds.
  # Fix such failures by rewriting content instead of injecting filler.

  $autoPadUsed = $false

  # English gates: if afterword exceeds max words, trim to max while preserving original characters.
  if (($maxAfterwordWords -gt 0) -and ($afterWords -gt $maxAfterwordWords)) {
    $ms = $WordRe.Matches($after)
    if ($ms.Count -ge $maxAfterwordWords) {
      $last = $ms[$maxAfterwordWords - 1]
      $cut = $last.Index + $last.Length
      if ($cut -gt 0 -and $cut -le $after.Length) {
        $after = $after.Substring(0, $cut).TrimEnd() + "`n"
        $afterWords = $WordRe.Matches($after).Count
        $changed = $true
      }
    }
  }

  # Recompose
  $newText = (ConvertTo-NormalizedText -Text $body).TrimEnd() + "`n`n$marker`n" + (ConvertTo-NormalizedText -Text $after)

  # Safety: keep English afterword free of CJK when maxAfterwordCJK == 0
  if (($maxAfterwordCJK -eq 0) -and ($CjkRe.Matches($after).Count -gt 0)) {
    $results += [pscustomobject]@{ platform=$platform; path=$path; action='blocked_afterword_cjk'; changed=$false }
    continue
  }

  # Safety: keep whole file free of CJK when maxTotalCJK == 0
  if ($requireNoCJK -and ($CjkRe.Matches($newText).Count -gt 0)) {
    $results += [pscustomobject]@{ platform=$platform; path=$path; action='blocked_total_cjk'; changed=$false }
    continue
  }

  if ($changed -and (-not $WhatIf)) {
    Set-Content -LiteralPath $path -Value $newText -Encoding UTF8
  }

  # Report updated metrics (without printing正文)
  $parts2 = Split-BodyAfterword -Text $newText -Marker $marker
  $body2 = [string]$parts2[0]
  $after2 = [string]$parts2[1]
  $results += [pscustomobject]@{
    platform = $platform
    path = $path
    changed = $changed
    autoPadUsed = $autoPadUsed
    allowAutoPad = $false
    body_cjk = $CjkRe.Matches($body2).Count
    body_len = $body2.Length
    afterword_cjk = $CjkRe.Matches($after2).Count
    afterword_words = $WordRe.Matches($after2).Count
  }
}

$results | Format-Table -AutoSize
