<#
.SYNOPSIS
  Reduce highly formulaic pad-like one-line sentences in Chinese BODY.

.DESCRIPTION
  This is a readability repair step. It targets lines that look like the synthetic
  one-liners generated by append_cn_unique_narration.ps1 (or similar), and removes
  most of them while preserving the real narrative.

  IMPORTANT
  - Earlier versions matched only whole lines. If pad-like sentences were packed
    into a single long paragraph line, they could evade detection.
  - This version detects/removes pad-like *sentences* inside lines, while keeping
    non-pad content intact.

  - Operates ONLY on BODY (text before marker). Afterword untouched.
  - Does not print chapter正文; prints numeric metrics only.
  - Keeps all non pad-like lines.
  - Ensures BODY CJK remains >= MinBodyCJK (best-effort by keeping some pad lines).

USAGE
  pwsh -NoProfile -File ./scripts/reduce_pad_like_lines.ps1 -Path "豆瓣/...md" -Seed 93101 -KeepEvery 6 -MaxKeepRun 3 -MinBodyCJK 2700
#>

[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)]
  [string]$Path,

  [Parameter()]
  [string]$Marker = "",

  [Parameter()]
  [int]$Seed = 93101,

  # Keep 1 pad-like line out of every N encountered (approx). Larger => more aggressive removal.
  [Parameter()]
  [ValidateRange(1,50)]
  [int]$KeepEvery = 6,

  # Hard cap consecutive kept pad-like lines to avoid visible blocks.
  [Parameter()]
  [ValidateRange(0,20)]
  [int]$MaxKeepRun = 2,

  [Parameter()]
  [int]$MinBodyCJK = 3500,

  # Optional override pattern. If empty, uses a conservative built-in heuristic.
  [Parameter()]
  [AllowEmptyString()]
  [string]$PadLikePattern = "",

  # Dry-run: compute metrics + emit report, but do not overwrite the chapter file.
  [Parameter()]
  [switch]$NoWrite
)

Set-StrictMode -Version Latest

# NOTE: Windows PowerShell 5.1 may mis-parse UTF-8 scripts without BOM,
# corrupting non-ASCII string literals. Build the default marker from code
# points to keep behavior stable across hosts/encodings.
if ([string]::IsNullOrWhiteSpace($Marker)) {
  $Marker = ('## ' + [char]0x4F5C + [char]0x8005 + [char]0x6709 + [char]0x8BDD + [char]0x8BF4)
}

$CjkRe = [regex]'[\u4e00-\u9fff]'

function ConvertTo-NormalizedNewline {
  param([Parameter(Mandatory=$true)][string]$Text)
  # Normalize Windows/Mac newlines to LF.
  $t = $Text -replace "\r\n|\r", "`n"

  # Avoid -split quirks by using string.Split on the LF char.
  $lines = $t.Split([char]10, [System.StringSplitOptions]::None)
  for ($i = 0; $i -lt $lines.Count; $i++) { $lines[$i] = $lines[$i].TrimEnd() }
  $t2 = ($lines -join "`n")

  # Ensure exactly one terminal LF.
  $t2 = $t2.TrimEnd([char]10)
  return $t2 + "`n"
}

function New-Rng { param([int]$Seed) return [System.Random]::new($Seed) }

function Get-MaxRunLength {
  param(
    [Parameter(Mandatory=$true)]
    [bool[]]$Flags
  )
  $max=0;$run=0
  foreach ($f in $Flags) {
    if ($f) { $run++; if ($run -gt $max) { $max=$run } }
    else { $run=0 }
  }
  return [int]$max
}

function Split-LineToSentences {
  param(
    [Parameter(Mandatory=$true)]
    [AllowEmptyString()]
    [string]$Line
  )

  # Keep punctuation at end of each sentence. If no sentence-ending punctuation is
  # present, return the original line as a single segment.
  $ms = [regex]::Matches($Line, '[^。！？]*[。！？]')
  if ($ms.Count -eq 0) {
    return ,@($Line)
  }

  $parts = New-Object 'System.Collections.Generic.List[string]'
  foreach ($m in $ms) {
    [void]$parts.Add([string]$m.Value)
  }

  $last = $ms[$ms.Count - 1]
  $tailStart = $last.Index + $last.Length
  if ($tailStart -lt $Line.Length) {
    $tail = $Line.Substring($tailStart)
    if (-not [string]::IsNullOrWhiteSpace($tail)) {
      [void]$parts.Add($tail)
    }
  }

  return ,$parts.ToArray()
}

if (-not (Test-Path -LiteralPath $Path)) {
  throw "File not found: $Path"
}

$rawText = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
$raw_crlf = ([regex]::Matches($rawText, "\r\n")).Count
$raw_lf = ([regex]::Matches($rawText, "\n")).Count

$text = ConvertTo-NormalizedNewline -Text $rawText
$norm_crlf = ([regex]::Matches($text, "\r\n")).Count
$norm_lf = ([regex]::Matches($text, "\n")).Count

$idx = $text.IndexOf($Marker, [System.StringComparison]::Ordinal)
if ($idx -lt 0) {
  # Be permissive: some platform files might miss the marker due to manual edits.
  # Treat the whole file as BODY in that case.
  $idx = $text.Length
}

$body = $text.Substring(0, $idx)
$rest = $text.Substring($idx)

$lines = $body.Split([char]10, [System.StringSplitOptions]::None)

$defaultPattern = '^(?:她|他|我|顾芮|沈砚|台灯|纸面|封条|文件袋|那点灰|那束光|那口气|那段静|纸面那道白|门禁的余响|封签那条线).+，(?:于是|可|然而|说到底|更要命的是|严格来说|换句话说|偏偏|从逻辑上讲|从程序上讲|也就是说|可问题在于|所以|便|说真的|然后|因此|与此同时|讲白了|说白了|归根结底|更准确地说|但是).*(?:先把|先别|别急着|按理讲|讲白了|更准确地说|只求|不求).*[。！？]$'
$rx = if ([string]::IsNullOrWhiteSpace($PadLikePattern)) { [regex]$defaultPattern } else { [regex]$PadLikePattern }

# Build sentence segments per line and locate pad-like sentence units.
$lineSegs = New-Object 'System.Collections.Generic.List[object]'
$padUnits = New-Object 'System.Collections.Generic.List[object]'
$lineHasPadBefore = New-Object 'System.Collections.Generic.List[bool]'
for ($i=0; $i -lt $lines.Count; $i++) {
  $segs = Split-LineToSentences -Line $lines[$i]
  [void]$lineSegs.Add($segs)
  $has = $false
  for ($j=0; $j -lt $segs.Count; $j++) {
    $seg = [string]$segs[$j]
    if ($rx.IsMatch($seg.Trim())) {
      $has = $true
      [void]$padUnits.Add([pscustomobject]@{ key = "${i}:${j}"; line = $i; seg = $j })
    }
  }
  [void]$lineHasPadBefore.Add([bool]$has)
}

$bodyCjkBefore = $CjkRe.Matches($body).Count
$padLikeLinesBefore = @($lineHasPadBefore | Where-Object { $_ }).Count
$padLikeSentencesBefore = $padUnits.Count
$maxRunBefore = Get-MaxRunLength -Flags ($lineHasPadBefore.ToArray())

$rng = New-Rng -Seed $Seed


# Decide which pad-like lines are eligible to keep (sampling phase). We'll still
# enforce MinBodyCJK during the build phase (so we never need to add back lines).
$keptPad = @{}
$keptRun = 0
$seenPad = 0

foreach ($u in $padUnits) {
  $seenPad++

  # Keep roughly 1 out of KeepEvery.
  $keep = (($seenPad % $KeepEvery) -eq 0)

  # Also apply RNG jitter so different files don't align.
  if (-not $keep) {
    if ($rng.NextDouble() -lt (1.0 / [Math]::Max(2, ($KeepEvery * 2)))) {
      $keep = $true
    }
  }

  if ($MaxKeepRun -eq 0) { $keep = $false }

  if ($keep) {
    if ($keptRun -ge $MaxKeepRun) {
      $keep = $false
    } else {
      $keptPad[[string]$u.key] = $true
      $keptRun++
    }
  }

  if (-not $keep) {
    $keptRun = 0
  }
}

# Build lines while enforcing MinBodyCJK (no add-back phase).
$outLines = New-Object 'System.Collections.Generic.List[string]'
$removed = 0
$removedSentences = 0
$forcedKeptDueToMin = 0
$bodyCjkWorking = $bodyCjkBefore
for ($i=0; $i -lt $lines.Count; $i++) {
  $segs = $lineSegs[$i]
  if ($null -eq $segs) {
    $outLines.Add($lines[$i])
    continue
  }

  $sb = New-Object System.Text.StringBuilder
  $lineRemovedAny = $false
  for ($j=0; $j -lt $segs.Count; $j++) {
    $seg = [string]$segs[$j]
    if ($rx.IsMatch($seg.Trim())) {
      $segCjk = $CjkRe.Matches($seg).Count
      $key = "${i}:${j}"

      $keep = $keptPad.ContainsKey($key)
      if (-not $keep) {
        # If removing would violate MinBodyCJK, force keep.
        if (($bodyCjkWorking - $segCjk) -lt $MinBodyCJK) {
          $keep = $true
          $forcedKeptDueToMin++
        }
      }

      if ($keep) {
        [void]$sb.Append($seg)
      } else {
        $lineRemovedAny = $true
        $removedSentences++
        $bodyCjkWorking -= $segCjk
        continue
      }
    } else {
      [void]$sb.Append($seg)
    }
  }

  $newLine = $sb.ToString().TrimEnd()
  if ($lineRemovedAny -and [string]::IsNullOrWhiteSpace($newLine) -and (-not [string]::IsNullOrWhiteSpace($lines[$i]))) {
    # Preserve paragraph boundaries if a non-empty line becomes empty.
    $newLine = ""
    $removed++
  }
  # Collapse excessive blank runs created by removals.
  if ([string]::IsNullOrEmpty($newLine)) {
    if ($outLines.Count -gt 0 -and [string]::IsNullOrEmpty($outLines[$outLines.Count - 1])) {
      continue
    }
  }
  $outLines.Add($newLine)
}

$body2 = ($outLines.ToArray() -join "`n")
$body2 = ConvertTo-NormalizedNewline -Text $body2

$addedBack = 0

$outText = ConvertTo-NormalizedNewline -Text ($body2 + $rest)

if (-not $NoWrite) {
  # Safety: refuse to overwrite a non-trivial file with an unexpectedly short output.
  # This prevents catastrophic truncation in case marker parsing/splitting fails.
  if ($rawText.Length -ge 1000) {
    $minOut = [Math]::Max(500, [int]($rawText.Length * 0.6))
    if ($outText.Trim().Length -lt $minOut) {
      throw "Refusing to overwrite '$Path': output too short (${($outText.Trim().Length)}) compared to input (${($rawText.Length)})."
    }
  }

  [System.IO.File]::WriteAllText((Resolve-Path -LiteralPath $Path).Path, $outText, [System.Text.Encoding]::UTF8)
}

# Post metrics
$afterLines = $body2.Split([char]10, [System.StringSplitOptions]::None)
$lineHasPadAfter = New-Object 'System.Collections.Generic.List[bool]'
$padLikeSentencesAfter = 0
for ($i=0; $i -lt $afterLines.Count; $i++) {
  $segs2 = Split-LineToSentences -Line $afterLines[$i]
  $has2 = $false
  for ($j=0; $j -lt $segs2.Count; $j++) {
    if ($rx.IsMatch(([string]$segs2[$j]).Trim())) {
      $has2 = $true
      $padLikeSentencesAfter++
    }
  }
  [void]$lineHasPadAfter.Add([bool]$has2)
}
$padAfter = @($lineHasPadAfter | Where-Object { $_ }).Count
$maxRunAfter = Get-MaxRunLength -Flags ($lineHasPadAfter.ToArray())

$report = [pscustomobject]@{
  path = $Path
  seed = $Seed
  keepEvery = $KeepEvery
  maxKeepRun = $MaxKeepRun
  minBodyCJK = $MinBodyCJK
  pad_like_pattern = $rx.ToString()
  raw_crlf = $raw_crlf
  raw_lf = $raw_lf
  normalized_crlf = $norm_crlf
  normalized_lf = $norm_lf
  body_line_count = $lines.Count
  body_cjk_before = $bodyCjkBefore
  body_cjk_after = $CjkRe.Matches($body2).Count
  pad_like_lines_before = $padLikeLinesBefore
  pad_like_sentences_before = $padLikeSentencesBefore
  pad_like_max_run_before = $maxRunBefore
  pad_like_lines_after = $padAfter
  pad_like_sentences_after = $padLikeSentencesAfter
  pad_like_max_run_after = $maxRunAfter
  removed_pad_lines = $removedSentences
  removed_pad_sentences = $removedSentences
  added_back_lines = $addedBack
  forced_kept_due_to_min = $forcedKeptDueToMin
}

$leaf = (Split-Path -Leaf $Path)
$reportPath = "SOP执行日志/reduce_pad_like_${Seed}_$leaf.json"
$report | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $reportPath -Encoding UTF8

$report | Format-Table -AutoSize
